name: "Build PyPI Nightly"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day

jobs:
  calculate-version:
    name: "Calculate Version"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'HumanSignal'
    outputs:
      version: ${{ steps.set-nightly-version.outputs.version }}
    steps:
      - name: Set nightly version
        id: set-nightly-version
        run: |
          set -e
          version=$(curl -s "https://raw.githubusercontent.com/HumanSignal/label-studio/refs/heads/${{ github.event.repository.default_branch }}/pyproject.toml" | grep '^version' | cut -d'"' -f2)
          version="${version%dev*}dev$(date +'%Y%m%d')"
          echo "version=${version}" >> $GITHUB_OUTPUT

  create-nightly-release:
    name: "Create Nightly Release"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'HumanSignal'
    needs: calculate-version
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Get previous nightly release
        id: previous-nightly
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const { repo, owner } = context.repo;
            try {
              const nightlyRelease = await github.rest.repos.getReleaseByTag({
                owner,
                repo,
                tag: 'nightly'
              });
              
              await github.rest.repos.deleteRelease({
                owner,
                repo,
                release_id: nightlyRelease.data.id
              });
              
              core.setOutput('tag_name', nightlyRelease.data.tag_name);
            } catch (error) {
              if (error.status === 404) {
                console.log('No previous nightly release found');
              } else {
                throw error;
              }
            }

      - name: Create Nightly Release
        id: create_release
        uses: softprops/action-gh-release@v2.2.1
        with:
          token: ${{ secrets.GIT_PAT }}
          tag_name: nightly
          name: "Nightly"
          generate_release_notes: false
          draft: false
          prerelease: true
          append_body: false

  build-pypi:
    name: "Build"
    if: github.repository_owner == 'HumanSignal'
    needs: [calculate-version, create-nightly-release]
    permissions:
      contents: write
    uses: ./.github/workflows/build_pypi.yml
    with:
      version: ${{ needs.calculate-version.outputs.version }}
      ref: ${{ github.ref_name }}
      upload_to_pypi: false
      release_type: nightly
      release-id: ${{ needs.create-nightly-release.outputs.release_id }}
    secrets: inherit